---
- name: Install rust
  vars:
    profile: "{{ 'complete' if inventory_hostname == 'localhost' else 'default' }}"
  ansible.builtin.shell: |
    set -o pipefail;
    curl https://sh.rustup.rs -sSf | sh -s -- --profile={{ profile }} --no-modify-path -y
  changed_when: true
  tags:
    - dev
    - update
    - rust

- name: Set rust to stable version
  ansible.builtin.shell: |
    $CARGO_HOME/bin/rustup set profile default
    $CARGO_HOME/bin/rustup default stable
  changed_when: true
  tags:
    - dev
    - update
    - rust

- name: Install core tools
  ansible.builtin.shell: $CARGO_HOME/bin/cargo install {{ item }}
  changed_when: true
  loop:
    - eza
    - zoxide
  tags:
    - dev
    - update
    - rust

- name: Install dev tools
  ansible.builtin.shell: $CARGO_HOME/bin/cargo install {{ item }}
  changed_when: true
  loop:
    - eva
    - ripgrep
    - du-dust
    - hyperfine
    - bandwhich
    - sd
    - procs
    - tealdeer
    - fd-find
    - silicon
  tags:
    - dev
    - update
    - rust

- name: Install stylua
  ansible.builtin.shell: $CARGO_HOME/bin/cargo install {{ item }}
  changed_when: true
  loop:
    - stylua
  tags:
    - dev
    - neovim
    - rust
