#!/usr/bin/env sh

PROJECT_PATH=$(git rev-parse --show-toplevel)
UNENCRYPTED_FILES="$(grep -rLE "ANSIBLE_VAULT" "$PROJECT_PATH/secrets")"

if [ -n "$UNENCRYPTED_FILES" ]; then
  echo "These files are not encrypted !"
  echo "$UNENCRYPTED_FILES";
fi
docker run -v "$PROJECT_PATH:/opt" --rm --workdir /opt aquasec/trivy -q fs --exit-code 1 --no-progress .
