#!/usr/bin/env sh

UNENCRYPTED_FILES="$(grep -rLE "ANSIBLE_VAULT" "$(git rev-parse --show-toplevel)/secrets")"

if [ -n "$UNENCRYPTED_FILES" ]; then
  echo "These files are not encrypted !"
  echo "$UNENCRYPTED_FILES";
  exit 1
fi

#
