- hosts: localhost
  vars:
    source_key: "./secrets/ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.secrets/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/private"
    me: "{{ lookup('env', 'USER') }}"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
#    - include: tasks/secrets.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/1password.yml
    - include_tasks: tasks/core-alternatives.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/neovim.yml

