- hosts: localhost
  vars:
    source_key: "./secrets/ssh/id_rsa"
    source_key_pub: "./secrets/ssh/id_rsa.pub"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    dest_key_pub: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    personal: "{{ lookup('env', 'HOME') }}/private"
    me: "{{ lookup('env', 'USER') }}"
    cfg_cmd: "git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
#    - include: tasks/secrets.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/1password.yml
    - include_tasks: tasks/core-alternatives.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/neovim.yml

