all:
  vars:
    marker: SETUP

k8s_nodes:
  hosts:
    ilum:
      ansible_host: ilum.local.j-p.cloud
  vars:
    ansible_user: p
    SYSTEM_TYPE: SERVER
# server_nodes:
#   hosts:
#     truenas:
#       ansible_host: 10.10.1.11
#     misc_nuc:
#       ansible_host: 10.10.1.9
#   vars:
#     ansible_user: p
#     SYSTEM_TYPE: SERVER
