---
- name: Install System Packages
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - software-properties-common
      - cmake
      - pkg-config
      - stow
      - lua5.1
      - unzip
      - libtool
      - libtool-bin
      - gettext
      - curl
      - wget
      - openssh-client
      - fontconfig
      - unzip
      - zip
      - jq
      - htop
      - git
      - nmap
      - imagemagick
      - python3-venv
      - tmux
      - yamllint
      - wslu
      - xdg-utils
      - apache2-utils
      - ffmpeg
      - net-tools
      - xsel
      - gnupg2
  tags:
    - install
    - core

- name: Setup Directories
  become: true
  ansible.builtin.file:
    path: "/opt"
    state: directory
    owner: "{{ me }}"
    group: "{{ me }}"
    mode: "0755"
    recurse: true
# - name: Setup Directories
#   ansible.builtin.file:
#     path: "$XDG_RUNTIME_DIR"
#     state: directory
#     owner: "{{ me }}"
#     group: "{{ me }}"
#     mode: "0700"
