- name: Create git-dir
  file:
    path: "{{ lookup('env', 'HOME') }}/.cfg"
    state: 'directory'

- name: Alias dotfile bare repo
  shell: "{{ cfg_cmd }} {{ item }}"
  loop:
    - init -b main
    - remote add origin git@github.com:ppfenning92/dotfiles.git
    - fetch --all
    - checkout -f main
    - reset --hard

- name: get env-files
  find:
    paths: "{{ lookup('env', 'HOME') }}/.config"
    file_type: file
    recurse: yes
    patterns: [ '*.env' ]
  register: env_files

- name: test sql copy
  copy:
    src: "{{ item.path }}"
    dest: "{{ item.path }}"
  loop: "{{ env_files.files | list }}"
