- name: Create git-dir
  file:
    path: "{{ lookup('env', 'HOME') }}/.cfg"
    state: 'directory'

- name: Alias dotfile bare repo
  shell: "{{ cfg_cmd }} {{ item }}"
  loop:
    - init -b main
    - remote add origin git@github.com:ppfenning92/dotfiles.git
    - fetch --all
    - checkout -f main
    - reset --hard