- name: Create git-dir
  file:
    path: "{{ lookup('env', 'HOME') }}/.cfg"
    state: 'directory'

- name: Alias dotfile bare repo
  shell: |
    {{ cfg_cmd }} init -b main
    {{ cfg_cmd }} remote add origin git@github.com:ppfenning92/dotfiles.git
    {{ cfg_cmd }} fetch --all
    {{ cfg_cmd }} checkout -f main
    {{ cfg_cmd }} reset --hard