---
- name: Get dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:ppfenning92/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true

- name: Remove default .bashrc
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: absent

- name: Stow
  ansible.builtin.command: chdir={{ lookup('env', 'HOME') }}/.dotfiles stow . -d . -t "{{ lookup('env', 'HOME') }}"

- name: Set disable admin-flag file
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/disable_admin_flag
    state: touch
    mode: "644"

- name: Set disable admin-flag file
  become: true
  ansible.builtin.blockinfile:
    marker: "### ANSIBLE MANAGED"
    path: /etc/sudoers.d/disable_admin_flag
    insertafter: EOF
    block: |
      Defaults !admin_flag
