---
- name: Download repository
  ansible.builtin.git:
    repo: https://github.com/eradman/entr
    dest: /opt/entr
    force: true
    update: true
  tags: &entr_tags
    - entr
    - install

- name: Run configure
  ansible.builtin.shell:
    cmd: ./configure
    chdir: /opt/entr/
  tags: *entr_tags

- name: Make test
  ansible.builtin.make:
    chdir: /opt/entr/
    target: test
  <<: *entr_tags

- name: Make install
  ansible.builtin.make:
    chdir: /opt/entr/
    target: install
  tags: *entr_tags
