- name: Download go
  get_url:
    url: https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
    dest: /tmp/go1.20.5.tar.gz

- name: Extract go
  become: true
  unarchive:
    src: /tmp/go1.20.5.tar.gz
    dest: /usr/local

- name: Remove installer
  file:
    path: /tmp/go1.20.5.tar.gz
    state: absent

- name: go tools
  shell: |
    GOPATH="$XDG_DATA_HOME"/go /usr/local/go/bin/go install {{ item }}
  loop:
    - github.com/charmbracelet/glow@latest
    - github.com/charmbracelet/gum@latest
    - github.com/incu6us/goimports-reviser/v3@latest
    - mvdan.cc/gofumpt@latest
    - github.com/segmentio/golines@latest
