- name: Download go
  get_url:
    url: https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
    dest: /tmp/go1.20.5.tar.gz

- name: Extract go
  become: true
  unarchive:
    src: /tmp/go1.20.5.tar.gz
    dest: /usr/local

- name: Remove installer
  file:
    path: /tmp/go1.20.5.tar.gz
    state: absent

- name: go tools
  shell: /usr/local/go/bin/go install {{ item }}
  loop:
    - github.com/charmbracelet/glow@latest
