---
- name: Download go
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.22.0.linux-amd64.tar.gz
    dest: /tmp/go1.22.0.tar.gz
    mode: "0644"
  tags: ["go", "install"]

- name: Extract go
  become: true
  ansible.builtin.unarchive:
    src: /tmp/go1.22.0.tar.gz
    dest: /usr/local
  tags: ["go", "install"]

- name: Remove installer
  ansible.builtin.file:
    path: /tmp/go1.22.0.tar.gz
    state: absent
  tags: ["go", "install"]

- name: Go tools
  ansible.builtin.shell: |
    GOPATH="$XDG_DATA_HOME"/go /usr/local/go/bin/go install {{ item }}
  changed_when: true
  loop:
    - github.com/charmbracelet/glow@latest
    - github.com/charmbracelet/gum@latest
    - github.com/incu6us/goimports-reviser/v3@latest
    - mvdan.cc/gofumpt@latest
    - github.com/segmentio/golines@latest
    - github.com/jesseduffield/lazydocker@latest
  tags: ["go", "install"]
