---
- name: Install rust
  ansible.builtin.shell: |
    set -o pipefail;
    curl https://sh.rustup.rs -sSf | sh -s -- --profile=complete --no-modify-path -y
  changed_when: true
  tags:
    - install
    - update
    - rust

- name: Set rust to stable version
  ansible.builtin.shell: $CARGO_HOME/bin/rustup default stable
  changed_when: true
  tags:
    - install
    - update
    - rust

- name: Install tools
  ansible.builtin.shell: $CARGO_HOME/bin/cargo install {{ item }}
  changed_when: true
  loop:
    - ripgrep
    - du-dust
    - hyperfine
    - bandwhich
    # - ytop
    - sd
    - eva
    - procs
    - tealdeer
    - fd-find
    - bat
    - zoxide
    - jql
    - silicon
  tags:
    - install
    - update
    - rust
    - full
