- name: Install rust
  shell: curl https://sh.rustup.rs -sSf | sh -s -- --profile=complete --no-modify-path -y
  tags:
    - install
    - productivity

- name: Set rust to stable version
  shell: $CARGO_HOME/bin/rustup default stable
  tags:
    - install
    - productivity

- name: install tools
  shell: $CARGO_HOME/bin/cargo install {{ item }}
  loop:
    - ripgrep
    - du-dust
    - hyperfine
    - bandwhich
    - ytop
    - sd
    - eva
    - procs
    - tealdeer
    - fd-find
    - bat
    - jql
    - --locked --features clipboard broot
  tags:
    - install
    - productivity
