---
- name: Ensure directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    owner: "{{ me }}"
    group: "{{ me }}"
    mode: "0700"
  tags:
    - ssh
    - install

- name: Copy public key
  ansible.builtin.copy:
    dest: "{{ dest_key_pub }}"
    src: "{{ source_key_pub }}"
    mode: "0644"
  tags:
    - ssh
    - install

- name: Copy private key
  ansible.builtin.copy:
    dest: "{{ dest_key }}"
    src: "{{ source_key }}"
    mode: "0600"
  tags:
    - ssh
    - install

- name: Set git known_hosts
  ansible.builtin.shell: |
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
  tags:
    - ssh
    - install
