---
- name: Install System Packages
  become: true
  changed_when: true
  ansible.builtin.git:
    repo: https://github.com/b3nj5m1n/xdg-ninja.git
    depth: 1
    dest: /opt/xdg-ninja
    update: true
    force: true

- name: Downloaf fzf from git
  become: true
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: /opt/fzf
    force: true

- name: Glamour themes
  become: true
  ansible.builtin.git:
    repo: https://github.com/catppuccin/glamour.git
    version: v1.0.0
    dest: /opt/catppuccin/glamour
    force: true

- name: Opt permissions
  become: true
  ansible.builtin.file:
    path: /opt
    state: directory
    group: "{{ me }}"
    owner: "{{ me }}"
    recurse: true

- name: Install fzf
  ansible.builtin.shell: |
    bash -c "/opt/fzf/install --all --xdg --key-bindings --completion --no-update-rc"
  changed_when: true

- name: Build Glamour
  become: true
  changed_when: true
  ansible.builtin.shell: |
    chdir=/opt/catppuccin/glamour/
    pip install -r requirements.txt 
    python src/generate.py
