---
- name: Get dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:ppfenning92/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    recursive: true
    update: true
    force: true

- name: Remove default .bashrc
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: absent

- name: Stow
  ansible.builtin.command: chdir={{ ansible_env.HOME) }}/.dotfiles stow . -d . -t "{{ ansible_env.HOME }}"

- name: Set disable admin-flag file
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/disable_admin_flag
    state: touch
    mode: "644"

- name: Set disable admin-flag file
  become: true
  ansible.builtin.blockinfile:
    marker: "### ANSIBLE MANAGED"
    path: /etc/sudoers.d/disable_admin_flag
    insertafter: EOF
    block: |
      Defaults !admin_flag
