---
- name: Install System Packages
  become: true
  changed_when: true
  ansible.builtin.git:
    repo: https://github.com/b3nj5m1n/xdg-ninja.git
    depth: 1
    dest: /opt/xdg-ninja
    update: true
    force: true
  tags: ["dev", "tool"]

- name: "Set httpie apt repo"
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    curl -SsL https://packages.httpie.io/deb/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/httpie.gpg
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./" | sudo tee /etc/apt/sources.list.d/httpie.list > /dev/null

- name: "update apt"
  become: true
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
    state: present

- name: "install httpie"
  become: true
  ansible.builtin.apt:
    name:
      - httpie
  tags: ["dev", "tool"]
