---
- include_tasks: btop.yml
  tags: [ "core", "tool" ]
- include_tasks: misc.yml
  tags: [ "core", "tool" ]
- include_tasks: entr.yml
  tags: [ "dev", "tool" ]
  when: inventory_hostname == "localhost"
- include_tasks: localhost.yml
  tags: [ "dev", "tool" ]
  when: inventory_hostname == "localhost"
