---
- name: Downloaf fzf from git
  become: true
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: /opt/fzf
    force: true
  tags: [ "core", "tool" ]

- name: Glamour themes
  become: true
  ansible.builtin.git:
    repo: https://github.com/catppuccin/glamour.git
    version: v1.0.0
    dest: /opt/catppuccin/glamour
    force: true
  tags: [ "core", "tool" ]

- name: Install fzf
  ansible.builtin.shell: |
    bash -c "/opt/fzf/install --all --xdg --key-bindings --completion --no-update-rc"
  changed_when: true
  tags: [ "core", "tool" ]

- name: Build Glamour
  become: true
  changed_when: true
  ansible.builtin.shell: |
    chdir=/opt/catppuccin/glamour/
    pip install -r requirements.txt 
    python src/generate.py
  tags: [ "core", "tool" ]


