---
- name: Ensure nvm dir exits
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/nvm"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags:
    - node
    - dev

- name: Nvm
  ansible.builtin.shell: |
    set -o pipefail
    PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash'
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/nvm"
  tags:
    - node
    - dev

- name: Install bun
  ansible.builtin.shell: |
    set -o pipefail
    curl -fSsL https://bun.sh/install | bash
  environment:
    BUN_INSTALL: "{{ ansible_env.HOME }}/.local/share/bun"
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/bun"
  tags:
    - node
    - dev
