---
- name: Clone Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ ansible_env.HOME }}/neovim"
    update: true
  changed_when: true
  tags:
    - core
    - neovim

- name: Build neovim
  ansible.builtin.shell: "cd {{ ansible_env.HOME }}/neovim && make -j 20"
  changed_when: true
  tags:
    - core
    - neovim

- name: Install neovim
  become: true
  ansible.builtin.shell: "cd {{ ansible_env.HOME }}/neovim && make install"
  changed_when: true
  tags:
    - core
    - neovim

- name: Neovim Plugin Development 1
  become: true
  ansible.builtin.apt:
    name:
      - luarocks
  tags:
    - dev
    - neovim

- name: Neovim Plugin Development 2 luacheck
  become: true
  ansible.builtin.command: luarocks install luacheck
  changed_when: true
  tags:
    - dev
    - neovim

- name: Install stylua
  ansible.builtin.shell: $CARGO_HOME/bin/cargo install {{ item }}
  changed_when: true
  loop:
    - stylua
  tags:
    - dev
    - neovim
    - rust

- name: Remove neovim src dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/neovim"
    state: absent
  tags:
    - core
    - neovim
